server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: PrometheusDemoApplication
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

management:
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8087
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        metrics: metrics_names
        prometheus: metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always